[build]
    base = "apps/app"
    command = "pnpm i --frozen-lockfile && pnpm build"
    publish = "dist/client"

[build.environment]
    NODE_VERSION = "22"

[[redirects]]
    from = "/*"
    to = "/.netlify/functions/server"
    status = 200