[build]
base = "apps/app"
command = "pnpm exec vite build --root src/renderer"
publish = "dist"

[functions]
directory = ".netlify/v1/functions"
node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
