packages:
    - apps/*
    - packages/*
    - tooling/*

nodeLinker: hoisted

onlyBuiltDependencies:
    - "@parcel/watcher"
    - "@sentry-internal/node-cpu-profiler"
    - "@sentry/cli"
    - "@shopify/react-native-skia"
    - "@swc/core"
    - bcrypt
    - bufferutil
    - core-js
    - core-js-pure
    - deasync
    - esbuild
    - fsevents
    - parcel-bundler
    - protobufjs
    - sharp
    - unrs-resolver
    - zlib-sync

shamefullyHoist: true
