packages:
  - apps/*
  - packages/*
  - tooling/*

allowBuilds:
  '@discordjs/opus': true
  '@sentry-internal/node-cpu-profiler': true
  '@shopify/react-native-skia': true
  '@swc/core': true
  bcrypt: true
  bufferutil: true
  canvas: true
  electron: true
  esbuild: true
  keytar: true
  mediasoup: true
  sharp: true
  unrs-resolver: true
  zlib-sync: true

nodeLinker: hoisted
shamefullyHoist: true
blockExoticSubdeps: false

overrides:
  react: 19.2.0
  react-dom: 19.2.0
  react-native: 0.83.2
  "@types/react": 19.2.10
  "@types/react-dopm": 19.2.3
  "@emotion/react": 11.14.0
  "@emotion/styled": 11.14.1
  "@emotion/native": 11.11.0
  react-native-svg: 15.15.3
  "@shopify/react-native-skia": 2.4.18
  sharp: 0.34.5

dedupeDirectDeps: true
dedupeInjectedDeps: true
dedupePeerDependents: true
dedupePeers: true
minimumReleaseAgeExclude:
  - html-react-parser@6.1.3
