name: Announce Changes

on:
    workflow_dispatch:
    push:
        branches:
            - release

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - id: changelog
              run: |
                  if [ -f CHANGELOG.md ]; then
                    echo "body<<EOF" >> $GITHUB_OUTPUT
                    cat CHANGELOG.md >> $GITHUB_OUTPUT
                    echo "EOF" >> $GITHUB_OUTPUT
                  else
                    echo "body=" >> $GITHUB_OUTPUT
                  fi
              shell: bash

            - name: Discord Webhook
              uses: tsickert/discord-webhook@v7.0.0
              with:
                  webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL}}
                  username: "Changelog"
                  avatar-url: "https://cdn.discordapp.com/icons/1332254930861424661/6bf53396c2dbc48047f69f905a3cbe2a.webp?size=1024"
                  content: ${{ steps.changelog.outputs.body }}
