name: Debug Secret

on: workflow_dispatch

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret
        env:
          SECRET: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        run: echo "$SECRET"
